# Generated by Django 5.1.4 on 2024-12-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptrial',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyinstallations',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlypayments',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
    ]
