# Generated by Django 5.0.6 on 2024-06-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='label',
            field=models.CharField(default='<django.db.models.fields.CharField>_label', max_length=255, unique=True),
        ),
    ]
