# Generated by Django 5.0.6 on 2024-06-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_eventtype_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
