# Generated by Django 5.1.4 on 2025-01-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_messagessent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagessent',
            name='from_number',
        ),
    ]
