# Generated by Django 5.0.6 on 2024-06-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subscription_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
