# Generated by Django 5.0.6 on 2024-06-24 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_eventtype_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('pending_payment', 'بإنتظار الدفع'), ('pending_review', 'بإنتظار المراجعة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم التنفيذ'), ('in_delivery', '-- جاري التوصيل'), ('delivered', '-- تم التوصيل'), ('shipped', '-- تم الشحن'), ('cancelled', 'ملغي'), ('returned', 'مسترجع'), ('in_return', 'قيد الإسترجاع'), ('quotation_requested', 'طلب عرض سعر')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.eventtype'),
        ),
    ]
