# Generated by Django 5.0.6 on 2024-06-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userevent_subcategory_alter_userevent_event_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('store', 'event_type', 'subcategory')},
        ),
    ]
