# Generated by Django 5.0.6 on 2024-06-26 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_userevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('pending_payment', 'بإنتظار الدفع'), ('pending_review', 'بإنتظار المراجعة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم التنفيذ'), ('in_delivery', 'جاري التوصيل'), ('delivered', 'تم التوصيل'), ('shipped', 'تم الشحن'), ('cancelled', 'ملغي'), ('returned', 'مسترجع'), ('in_return', 'قيد الإسترجاع'), ('quotation_requested', 'طلب عرض سعر')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('clicks', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('msg', models.TextField()),
                ('customers_dict_json', models.TextField(default='{}')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.store')),
            ],
        ),
    ]
