# Generated by Django 5.0.6 on 2024-06-12 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_store_user_store_last_reset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('abandoned_cart', 'Abandoned Cart'), ('order_received', 'Order Received'), ('order_cancelled', 'Order Cancelled'), ('order_updated', 'Order Updated'), ('shipment_updated', 'Shipment Updated')], max_length=50)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
