# Generated by Django 5.0.6 on 2024-06-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userevent_subcategory_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
    ]
