# Generated by Django 5.0.6 on 2024-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_campaign_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='customers_dict_json',
            field=models.TextField(default=''),
        ),
    ]
