# Generated by Django 5.0.6 on 2024-06-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='message_content',
            new_name='abandoned_cart',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='event_type',
        ),
        migrations.AddField(
            model_name='userevent',
            name='order_cancelled',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='order_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='order_updated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='shipment_updated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
