# Generated by Django 5.0.6 on 2024-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_campaign_customers_dict_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='customers_dict_json',
        ),
        migrations.AddField(
            model_name='campaign',
            name='customers_group',
            field=models.CharField(default='o', max_length=255),
            preserve_default=False,
        ),
    ]
