# Generated by Django 5.0.6 on 2024-06-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_message_content_userevent_abandoned_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
        migrations.AddField(
            model_name='userevent',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
    ]
