# Generated by Django 5.0.6 on 2024-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_campaign_customers_dict_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
