# Generated by Django 5.0.6 on 2024-06-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_userevent_user_userevent_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
    ]
