# Generated by Django 5.0.6 on 2024-07-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
