# Generated by Django 5.0.6 on 2024-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
