# Generated by Django 5.0.6 on 2024-07-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
