# Generated by Django 5.0.6 on 2024-09-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
