# Generated by Django 5.0.6 on 2024-09-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_campaign_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='last_reset',
            new_name='subscription_date',
        ),
    ]
