# Generated by Django 5.0.6 on 2024-09-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_last_reset_store_subscription_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('step_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('delay', 'Time Delay'), ('condition', 'Condition')], max_length=50)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='base.flow')),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flowstep')),
            ],
        ),
        migrations.CreateModel(
            name='TextConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('flow_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_config', to='base.flowstep')),
            ],
        ),
        migrations.CreateModel(
            name='TimeDelayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_time', models.PositiveIntegerField()),
                ('delay_type', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], max_length=50)),
                ('flow_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_delay_config', to='base.flowstep')),
            ],
        ),
    ]
