# Generated by Django 5.0.6 on 2024-09-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_flowstep_step_type_flowstep_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstep',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.flowactiontypes'),
        ),
    ]
