# Generated by Django 5.0.6 on 2024-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_flowstep_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='reciepients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flow',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
