# Generated by Django 5.0.6 on 2024-10-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_trigger_flow_trigger_suggestedflow_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='base.trigger'),
        ),
        migrations.AlterField(
            model_name='suggestedflow',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_flows', to='base.trigger'),
        ),
    ]
