# Generated by Django 5.0.6 on 2024-10-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_textconfig_flow_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTextConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('suggested_flow_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_text_config', to='base.suggestedflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedTimeDelayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_time', models.PositiveIntegerField()),
                ('delay_type', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], max_length=50)),
                ('suggested_flow_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_time_delay_config', to='base.suggestedflowstep')),
            ],
        ),
    ]
