# Generated by Django 5.0.6 on 2024-10-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_suggestedtextconfig_suggestedtimedelayconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedtextconfig',
            name='suggested_flow_step',
            field=models.OneToOneField(limit_choices_to={'suggested_time_delay_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_text_config', to='base.suggestedflowstep'),
        ),
        migrations.AlterField(
            model_name='suggestedtimedelayconfig',
            name='suggested_flow_step',
            field=models.OneToOneField(limit_choices_to={'suggested_text_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_time_delay_config', to='base.suggestedflowstep'),
        ),
        migrations.AlterField(
            model_name='textconfig',
            name='flow_step',
            field=models.OneToOneField(limit_choices_to={'time_delay_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='text_config', to='base.flowstep'),
        ),
        migrations.AlterField(
            model_name='timedelayconfig',
            name='flow_step',
            field=models.OneToOneField(limit_choices_to={'text_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='time_delay_config', to='base.flowstep'),
        ),
    ]
