# Generated by Django 5.0.6 on 2024-10-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_suggestedtextconfig_suggested_flow_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstep',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='suggestedflowstep',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
