# Generated by Django 5.0.6 on 2024-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_flowstep_order_alter_suggestedflowstep_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstep',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='suggestedflowstep',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
