# Generated by Django 5.0.6 on 2024-10-05 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_flowstep_order_alter_suggestedflowstep_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstep',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='suggestedflowstep',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
