# Generated by Django 5.0.6 on 2024-10-06 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_flowstep_order_alter_suggestedflowstep_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstep',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='suggestedflowstep',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='flowstep',
            constraint=models.UniqueConstraint(fields=('flow', 'order'), name='unique_order_per_flowstep'),
        ),
        migrations.AddConstraint(
            model_name='suggestedflowstep',
            constraint=models.UniqueConstraint(fields=('suggested_flow', 'order'), name='unique_order_per_suggestedflowstep'),
        ),
    ]
