# Generated by Django 5.0.6 on 2024-10-07 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_flowstep_order_alter_suggestedflowstep_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
