# Generated by Django 5.0.6 on 2024-10-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_flow_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='flowstep',
            name='unique_order_per_flowstep',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='reciepients',
            new_name='recipients',
        ),
        migrations.AddField(
            model_name='flow',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='flowstep',
            constraint=models.UniqueConstraint(fields=('flow', 'order'), name='unique_order_per_flow'),
        ),
    ]
