# Generated by Django 5.0.6 on 2024-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_flow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowactiontypes',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
