# Generated by Django 5.0.6 on 2024-10-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_flowactiontypes_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
