# Generated by Django 5.0.6 on 2024-10-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_timedelayconfig_delay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedtimedelayconfig',
            name='delay_type',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('minutes', 'Minutes')], max_length=50),
        ),
    ]
