# Generated by Django 5.0.6 on 2024-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_suggestedtimedelayconfig_delay_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='message_count',
            new_name='subscription_message_count',
        ),
        migrations.AddField(
            model_name='store',
            name='total_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='total_messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='total_purchases',
            field=models.IntegerField(default=0),
        ),
    ]
