# Generated by Django 5.0.6 on 2024-10-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_flow_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='base.store'),
        ),
    ]
