# Generated by Django 5.0.6 on 2024-10-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_flow_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowstep',
            name='next_step',
        ),
    ]
