# Generated by Django 5.0.6 on 2024-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_flowstep_next_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='event_type',
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='store',
        ),
        migrations.AddField(
            model_name='campaign',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flow',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'مفعلة'), ('paused', 'موقوفة'), ('archived', 'محظورة')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
