# Generated by Django 5.0.6 on 2024-10-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_userevent_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='messages_sent',
        ),
    ]
