# Generated by Django 5.0.6 on 2024-10-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_campaign_messages_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
    ]
