# Generated by Django 5.0.6 on 2024-11-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_campaign_messages_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='total_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
