# Generated by Django 5.0.6 on 2024-11-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_group_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
