# Generated by Django 5.0.6 on 2024-11-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_group_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
