# Generated by Django 5.0.6 on 2024-11-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_group_group_id_alter_group_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
