# Generated by Django 5.0.6 on 2024-11-06 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_couponconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponconfig',
            name='flow_step',
            field=models.OneToOneField(limit_choices_to={'text_config__isnull': True, 'time_delay_config__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_config', to='base.flowstep'),
        ),
        migrations.AlterField(
            model_name='suggestedtextconfig',
            name='suggested_flow_step',
            field=models.OneToOneField(limit_choices_to={'suggested_coupon_config__isnull': True, 'suggested_time_delay_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_text_config', to='base.suggestedflowstep'),
        ),
        migrations.AlterField(
            model_name='suggestedtimedelayconfig',
            name='suggested_flow_step',
            field=models.OneToOneField(limit_choices_to={'suggested_coupon_config__isnull': True, 'suggested_text_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_time_delay_config', to='base.suggestedflowstep'),
        ),
        migrations.AlterField(
            model_name='textconfig',
            name='flow_step',
            field=models.OneToOneField(limit_choices_to={'coupon_config__isnull': True, 'time_delay_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='text_config', to='base.flowstep'),
        ),
        migrations.AlterField(
            model_name='timedelayconfig',
            name='flow_step',
            field=models.OneToOneField(limit_choices_to={'coupon_config__isnull': True, 'text_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='time_delay_config', to='base.flowstep'),
        ),
        migrations.CreateModel(
            name='SuggestedCouponConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة مئوية')], max_length=50)),
                ('amount', models.IntegerField()),
                ('expire_in', models.DateField()),
                ('maximum_amount', models.IntegerField()),
                ('free_shipping', models.BooleanField()),
                ('exclude_sale_products', models.BooleanField()),
                ('suggested_flow_step', models.OneToOneField(limit_choices_to={'suggested_text_config__isnull': True, 'suggested_time_delay_config__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_coupon_config', to='base.suggestedflowstep')),
            ],
        ),
    ]
