# Generated by Django 5.0.6 on 2024-11-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_couponconfig_flow_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponconfig',
            name='flow_step',
            field=models.OneToOneField(limit_choices_to={'text_config__isnull': True, 'time_delay_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_config', to='base.flowstep'),
        ),
        migrations.AlterField(
            model_name='suggestedcouponconfig',
            name='suggested_flow_step',
            field=models.OneToOneField(limit_choices_to={'suggested_text_config__isnull': True, 'suggested_time_delay_config__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_coupon_config', to='base.suggestedflowstep'),
        ),
    ]
