# Generated by Django 5.0.6 on 2024-11-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_couponconfig_expire_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponconfig',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='suggestedcouponconfig',
            name='coupon_code',
        ),
    ]
