# Generated by Django 5.0.6 on 2024-11-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_remove_couponconfig_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponconfig',
            name='maximum_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestedcouponconfig',
            name='maximum_amount',
            field=models.IntegerField(null=True),
        ),
    ]
