# Generated by Django 5.0.6 on 2024-11-07 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_couponconfig_maximum_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='token_refresh_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
