# Generated by Django 5.0.6 on 2024-11-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_store_token_refresh_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
