# Generated by Django 5.0.6 on 2024-11-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_customer_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponconfig',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
