# Generated by Django 5.0.6 on 2024-11-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_couponconfig_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('flow', 'Flow'), ('campaign', 'Campaign')], max_length=10)),
                ('source_id', models.UUIDField()),
                ('activity_type', models.CharField(choices=[('message', 'Message'), ('purchase', 'Purchase'), ('click', 'Click')], max_length=10)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='base.store')),
            ],
        ),
    ]
