# Generated by Django 5.0.6 on 2024-11-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flow',
            name='track',
            field=models.BooleanField(default=False),
        ),
    ]
