# Generated by Django 5.0.6 on 2024-11-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_activitylog_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'مفعلة'), ('paused', 'موقوفة'), ('archived', 'محظورة'), ('deleted', 'تم الحذف')], default='draft', max_length=20),
        ),
    ]
