# Generated by Django 5.0.6 on 2024-11-21 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_alter_flow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('message', 'رسائل'), ('purchase', 'مشتريات'), ('click', 'ضغطات')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='source_type',
            field=models.CharField(choices=[('flow', 'الأتمتة'), ('campaign', 'الحملة')], max_length=10),
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('cart_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bought', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to='base.store')),
            ],
        ),
    ]
