# Generated by Django 5.0.6 on 2024-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abandonedcart',
            name='flow_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
