# Generated by Django 5.0.6 on 2024-11-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_abandonedcart_flow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abandonedcart',
            name='flow_id',
            field=models.UUIDField(),
        ),
    ]
