# Generated by Django 5.0.6 on 2024-11-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_abandonedcart_flow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedcouponconfig',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
