# Generated by Django 5.0.6 on 2024-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_suggestedcouponconfig_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='staticbot',
            field=models.BooleanField(default=False),
        ),
    ]
