# Generated by Django 5.0.6 on 2024-11-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_subscription_staticbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
