# Generated by Django 5.0.6 on 2024-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_alter_abandonedcart_store_alter_activitylog_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='store_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
