# Generated by Django 5.0.6 on 2024-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_flow_store_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='store_domain',
        ),
        migrations.AddField(
            model_name='store',
            name='store_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
