# Generated by Django 5.0.6 on 2024-12-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_remove_flow_store_domain_store_store_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorelink',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.store'),
        ),
    ]
