# Generated by Django 5.0.6 on 2024-12-02 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_alter_userstorelink_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorelink',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
    ]
