# Generated by Django 5.0.6 on 2024-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_notification_staticbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorelink',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
