# Generated by Django 5.0.6 on 2024-12-04 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_userstorelink_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticBotStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.store')),
            ],
        ),
    ]
