# Generated by Django 5.0.6 on 2024-12-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_store_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
