# Generated by Django 5.0.6 on 2024-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_remove_store_phone_number_subscription_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
