# Generated by Django 5.0.6 on 2024-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_remove_subscription_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticbotstart',
            name='last_sent_to_customer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
