# Generated by Django 5.0.6 on 2024-12-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_staticbotstart_last_sent_to_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticbotstart',
            name='last_sent_to_customer',
        ),
        migrations.CreateModel(
            name='StaticBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staticbot')),
            ],
        ),
    ]
