# Generated by Django 5.0.6 on 2024-12-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_remove_staticbotstart_last_sent_to_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstorelink',
            name='enabled',
        ),
        migrations.AddField(
            model_name='staticbotstart',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='botenabled',
            field=models.BooleanField(default=False),
        ),
    ]
