# Generated by Django 5.0.6 on 2024-12-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_remove_userstorelink_enabled_staticbotstart_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticbotstart',
            name='condition',
            field=models.CharField(choices=[(1, 'النص بالضبط'), (2, 'يحتوي على النص'), (3, 'أي النص')], default=3, max_length=255),
        ),
        migrations.AlterField(
            model_name='staticbot',
            name='condition',
            field=models.CharField(choices=[(1, 'النص بالضبط'), (2, 'يحتوي على النص')], max_length=255),
        ),
    ]
