# Generated by Django 5.0.6 on 2024-12-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_alter_staticbot_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticbotlog',
            name='bot',
        ),
        migrations.AddField(
            model_name='staticbotlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
    ]
