# Generated by Django 5.0.6 on 2024-12-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_remove_staticbotlog_bot_staticbotlog_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticbotlog',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.store'),
        ),
    ]
