# Generated by Django 5.0.6 on 2024-12-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_staticbot_return_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticbotlog',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staticbotstart',
            name='condition',
            field=models.IntegerField(choices=[(1, 'النص بالضبط'), (2, 'يحتوي على النص'), (3, 'أي نص')], default=3),
        ),
        migrations.AlterUniqueTogether(
            name='staticbot',
            unique_together={('store', 'message')},
        ),
    ]
