# Generated by Django 5.0.6 on 2024-12-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_staticbotmessage_staticbotstartmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticbotstart',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='staticbotstart',
            name='message',
        ),
    ]
